name: Payment Required Build Pipeline

on:
  push:
    branches: [ feature/paymente-required ]
  pull_request:
    branches: [ feature/paymente-required ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build PaymentRequiredSolution.sln --configuration Release
    - name: Pack
      run: | 
        rm -rf dist/*.nupkg
        dotnet pack  --configuration Release --output dist/ --version-suffix "alpha.$env:GITHUB_SHA-$env:GITHUB_RUN_ATTEMPT"
        ls dist/*.nupkg
    # - name: Publish nuget.org
    #   run: dotnet nuget push dist/PaymentRequired.*.nupkg --api-key ${{secrets.NUGET_ORG}} --source https://api.nuget.org/v3/index.json
