name: Payment Required Build Pipeline

on:
  push:
    branches: [ feature/paymente-required ]
  pull_request:
    branches: [ feature/paymente-required ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      VERSION_SUFFIX: "alpha.${GITHUB_SHA}-${GITHUB_RUN_ATTEMPT}"
      CONFIGURATION: Release

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build PaymentRequiredSolution.sln --configuration $CONFIGURATION
    
    - name: Echos
      run: |
          echo ${GITHUB_SHA}
          echo ${GITHUB_RUN_ATTEMPT}
        
    - name: Pack
      run: | 
        rm -rf dist/*.nupkg
        dotnet pack  --configuration $CONFIGURATION --output dist/ --version-suffix "$VERSION_SUFFIX"
        ls dist/*.nupkg
    # - name: Publish nuget.org
    #   run: dotnet nuget push dist/PaymentRequired.*.nupkg --api-key ${{secrets.NUGET_ORG}} --source https://api.nuget.org/v3/index.json
