name: Payment Required Build Pipeline

on:
  push:
    branches: [ feature/paymente-required ]
  pull_request:
    branches: [ feature/paymente-required ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build PaymentRequiredSolution.sln --no-restore --configuration Release
    - name: Pack
      run: dotnet pack PaymentRequiredSolution.sln --no-restore --configuration Release --output dist/
    - name: Publish nuget.org
      run: dotnet nuget push dist/PaymentRequired.*.nupkg --skip-duplicate --no-symbols true --api-key ${{secrets.NUGET_ORG}} --source https://api.nuget.org/v3/index.json